### ISSUE TITLE
improve mobile style

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/default.css#6]
- minimum font size: 1rem
- reduce lateral padding

**Comment by waldyrious** [comment]
I wonder if there's a way to fix this using only css, though...

**Comment by waldyrious** [comment]
> I wonder if there's a way to fix this using only css, though...

[There is](https://benfrain.com/understanding-the-viewport-meta-tag-and-css-viewport/)!

```css
@viewport {
    width: device-width;
    initial-scale: 1;
}
```

It's [not ready for primetime yet](http://caniuse.com/#feat=css-deviceadaptation), but I should include it nevertheless.
