### ISSUE TITLE
investigate molten leading

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/default.css#9]
neater approach than fixed media-query-based breakpoints: https://css-tricks.com/molten-leading-css/

**Comment by waldyrious** [comment]
After some testing, I'm thinking of using on this:
```css
html { font-size: 1rem; }
@media (min-width: 100rem) { html { font-size: calc(0.4vw + .85rem) } }
```

or the equivalent in pixels:

```css
html { font-size: 16px; }
@media (min-width: 600px) { html { font-size: calc(0.4vw + 13.6px) } }
```

i.e. a constant line of 16px minimum font size for all viewports up to 600px, and from then on a linear progression based on the window width. For a smooth transition at the 600px mark, 0.4vw+13.6px should equal 16px. Since 1vw at 600px = 6, and 0.4*6 = 2.4, we need to sum 13.6 to get the 16px we started with as a minimum.

Perhaps I could set a smaller minimum, say 0.9rem.

And I wonder if we could get a smooth transition rather than a hard break. But using only elementary arithmetic operations it may become excessively convoluted.
